name: HTML to PDF
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: /index.html
          outputFile: /resume.pdf
          pdfOptions: '{"format": "A4", landscape: true, "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
